name: CI/CD para Angular no S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"  # Substitua com a região AWS onde está o seu bucket s3

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurando o NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalando as dependências do nosso projeto
      run: npm install

    - name: Buildando nosso projeto
      run: npm run build

    - name: Verificando arquivos gerados
      run: ls -la dist/portal-ex-colab

    - name: Verificando todos os arquivos gerados
      run: find dist/portal-ex-colab -type f

    - name: Configurando AWS CLI
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION

    - name: Verificando configuração AWS
      run: aws sts get-caller-identity

    - name: Realizando upload do bundle da aplicação no S3
      run: aws s3 sync dist/portal-ex-colab/browser s3://portal-ex-colab-github-s3 --delete

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Install k6-html-reporter
      run: npm install -g k6-html-reporter

    - name: Run load tests
      run: k6 run --out json=load-test-result.json load-test.js

    - name: Generate HTML report
      run: k6-html-reporter --json load-test-result.json --output load-test-report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: load-test-report
        path: load-test-report.html